config:
  activation: tanh
  bandwidth: 3.8e-03
  batch_size: 8
  coeff_cross_entropy: 9.4e-03
  coeff_entropy: 2.3e-02
  coeff_prior: 2.5e+00
  depth: 4
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 7.3e-04
  likelihood_prior_mean: 2.4e-03
  likelihood_prior_std: 5.3e-03
  n_iter: 10000
  n_particles: 10
  nn_prior_std: 5.3e-01
  noise_std: 1.4e-04
  prior_noise_std: 1.8e-04
  ssge_bandwidth: 3.7e-01
  ssge_eta: 1.2e-02
  ssge_n_eigen: 16
  val_fraction: 1.0e-01
  weight_decay: 4.1e-07
  width: 128
metrics:
  test_nll: -2.0e+00
  test_rmse: 9.8e-02
