config:
  activation: relu
  bandwidth: 2.9e-02
  batch_size: 8
  depth: 4
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 3.3e-03
  likelihood_prior_mean: 9.5e-04
  likelihood_prior_std: 2.3e-04
  n_iter: 10000
  n_particles: 5
  nn_prior_std: 8.8e-01
  noise_std: 1.1e-02
  val_fraction: 1.0e-01
  weight_decay: 8.2e-07
  width: 64
metrics:
  test_nll: 2.7e+01
  test_rmse: 1.2e-01
