config:
  activation: relu
  bandwidth: 6.5e-02
  batch_size: 32
  depth: 2
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 6.0e-04
  likelihood_prior_mean: 3.3e-02
  likelihood_prior_std: 8.9e-03
  n_iter: 10000
  n_particles: 15
  nn_prior_std: 1.0e+00
  noise_std: 1.4e-03
  val_fraction: 1.0e-01
  weight_decay: 1.8e-05
  width: 16
metrics:
  test_nll: -3.1e+00
  test_rmse: 1.1e-01
