config:
  activation: tanh
  bandwidth: 1.4e-02
  batch_size: 16
  coeff_cross_entropy: 8.9e-02
  coeff_entropy: 9.6e-03
  coeff_prior: 1.9e+00
  depth: 2
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 1.6e-04
  likelihood_prior_mean: 1.5e-03
  likelihood_prior_std: 6.8e-02
  n_iter: 10000
  n_particles: 50
  nn_prior_std: 1.4e+00
  noise_std: 2.2e-03
  prior_noise_std: 7.3e-05
  ssge_bandwidth: 2.2e+00
  ssge_eta: 2.0e-03
  ssge_n_eigen: 6
  val_fraction: 1.0e-01
  weight_decay: 1.2e-08
  width: 128
metrics:
  test_nll: 6.3e+01
  test_rmse: 2.2e-02
