config:
  activation: tanh
  bandwidth: 2.8e-02
  batch_size: 16
  coeff_cross_entropy: 8.4e-02
  coeff_entropy: 6.5e-02
  coeff_prior: 9.7e-01
  depth: 4
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 5.4e-03
  likelihood_prior_mean: 3.3e-02
  likelihood_prior_std: 2.6e-04
  n_iter: 10000
  n_particles: 10
  nn_prior_std: 1.2e+00
  noise_std: 1.7e-03
  prior_noise_std: 2.5e-05
  ssge_bandwidth: 2.8e+00
  ssge_eta: 6.2e-03
  ssge_n_eigen: 8
  val_fraction: 1.0e-01
  weight_decay: 9.0e-07
  width: 64
metrics:
  test_nll: -1.0e+00
  test_rmse: 1.5e-01
