config:
  activation: tanh
  bandwidth: 3.0e-02
  batch_size: 8
  coeff_cross_entropy: 1.3e-02
  coeff_entropy: 2.1e-02
  coeff_prior: 5.4e-01
  depth: 4
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 4.3e-04
  likelihood_prior_mean: 4.1e-02
  likelihood_prior_std: 9.1e-04
  n_iter: 10000
  n_particles: 30
  nn_prior_std: 7.3e-01
  noise_std: 2.0e-03
  prior_noise_std: 9.0e-03
  ssge_bandwidth: 1.4e+00
  ssge_eta: 1.5e-02
  ssge_n_eigen: 8
  val_fraction: 1.0e-01
  weight_decay: 4.0e-07
  width: 128
metrics:
  test_nll: 1.6e+03
  test_rmse: 2.2e+00
