config:
  activation: relu
  bandwidth: 1.0e-02
  batch_size: 8
  coeff_cross_entropy: 5.7e-03
  coeff_entropy: 1.6e-02
  coeff_prior: 1.5e-01
  depth: 2
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 3.4e-03
  likelihood_prior_mean: 8.2e-03
  likelihood_prior_std: 4.4e-04
  n_iter: 10000
  n_particles: 30
  nn_prior_std: 1.9e+00
  noise_std: 9.5e-04
  prior_noise_std: 3.2e-04
  ssge_bandwidth: 2.4e-01
  ssge_eta: 1.2e-02
  ssge_n_eigen: 4
  val_fraction: 1.0e-01
  weight_decay: 1.5e-06
  width: 32
metrics:
  test_nll: -2.8e+00
  test_rmse: 7.7e-02
