config:
  activation: tanh
  bandwidth: 4.8e-02
  batch_size: 32
  depth: 4
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 1.6e-04
  likelihood_prior_mean: 3.1e-04
  likelihood_prior_std: 4.1e-04
  n_iter: 10000
  nn_prior_std: 4.9e+00
  noise_std: 1.3e-02
  val_fraction: 1.0e-01
  weight_decay: 1.4e-07
  width: 128
metrics:
  test_nll: 2.7e+00
  test_rmse: 9.6e-01
