config:
  activation: elu
  bandwidth: 7.0e-03
  batch_size: 32
  depth: 2
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 3.4e-03
  likelihood_prior_mean: 1.6e-03
  likelihood_prior_std: 6.6e-03
  n_iter: 10000
  n_particles: 20
  nn_prior_std: 7.9e-01
  noise_std: 1.4e-03
  val_fraction: 1.0e-01
  weight_decay: 5.7e-08
  width: 16
metrics:
  test_nll: -2.9e+00
  test_rmse: 7.0e-01
