config:
  activation: tanh
  bandwidth: 1.2e-02
  batch_size: 4
  coeff_cross_entropy: 8.0e-03
  coeff_entropy: 2.5e-03
  coeff_prior: 1.7e+00
  depth: 4
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 7.8e-03
  likelihood_prior_mean: 6.7e-03
  likelihood_prior_std: 1.2e-04
  n_iter: 10000
  n_particles: 20
  nn_prior_std: 9.8e-01
  noise_std: 3.2e-04
  prior_noise_std: 6.4e-05
  ssge_bandwidth: 6.0e-01
  ssge_eta: 1.7e-02
  ssge_n_eigen: 4
  val_fraction: 1.0e-01
  weight_decay: 3.7e-06
  width: 16
metrics:
  test_nll: 2.4e+03
  test_rmse: 1.2e+00
