config:
  activation: elu
  bandwidth: 1.3e-03
  batch_size: 32
  coeff_cross_entropy: 1.6e-02
  coeff_entropy: 5.0e-02
  coeff_prior: 1.3e+00
  depth: 2
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 2.0e-04
  likelihood_prior_mean: 4.9e-02
  likelihood_prior_std: 3.6e-03
  n_iter: 10000
  n_particles: 15
  nn_prior_std: 1.1e+00
  noise_std: 3.8e-04
  prior_noise_std: 3.0e-04
  ssge_bandwidth: 1.5e-01
  ssge_eta: 4.0e-03
  ssge_n_eigen: 6
  val_fraction: 1.0e-01
  weight_decay: 8.9e-07
  width: 64
metrics:
  test_nll: -4.4e-01
  test_rmse: 6.6e-01
