config:
  activation: relu
  bandwidth: 6.0e-03
  batch_size: 32
  depth: 4
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 8.2e-04
  likelihood_prior_mean: 6.5e-03
  likelihood_prior_std: 1.2e-04
  n_iter: 10000
  n_particles: 50
  nn_prior_std: 1.1e+00
  noise_std: 2.3e-04
  val_fraction: 1.0e-01
  weight_decay: 2.9e-06
  width: 128
metrics:
  test_nll: 1.4e+01
  test_rmse: 7.0e-01
