config:
  activation: elu
  bandwidth: 2.0e-02
  batch_size: 16
  coeff_cross_entropy: 4.9e-02
  coeff_entropy: 4.8e-02
  coeff_prior: 1.0e+00
  depth: 4
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 9.2e-04
  likelihood_prior_mean: 5.5e-02
  likelihood_prior_std: 2.9e-03
  n_iter: 10000
  n_particles: 50
  nn_prior_std: 7.5e-01
  noise_std: 4.2e-03
  prior_noise_std: 1.3e-03
  ssge_bandwidth: 7.8e-01
  ssge_eta: 2.8e-02
  ssge_n_eigen: 4
  val_fraction: 1.0e-01
  weight_decay: 4.0e-06
  width: 32
metrics:
  test_nll: 1.8e+02
  test_rmse: 1.2e+00
