config:
  activation: relu
  bandwidth: 3.1e-02
  batch_size: 32
  coeff_cross_entropy: 6.7e-03
  coeff_entropy: 1.3e-02
  coeff_prior: 1.8e-01
  depth: 2
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 2.5e-03
  likelihood_prior_mean: 1.0e-01
  likelihood_prior_std: 1.6e-03
  n_iter: 10000
  n_particles: 10
  nn_prior_std: 1.6e+00
  noise_std: 1.3e-02
  prior_noise_std: 1.2e-04
  ssge_bandwidth: 2.1e+00
  ssge_eta: 2.5e-02
  ssge_n_eigen: 6
  val_fraction: 1.0e-01
  weight_decay: 9.7e-08
  width: 32
metrics:
  test_nll: -3.1e+00
  test_rmse: 5.5e-02
