config:
  activation: tanh
  bandwidth: 2.3e-03
  batch_size: 16
  depth: 2
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 1.5e-03
  likelihood_prior_mean: 2.3e-02
  likelihood_prior_std: 1.0e-02
  n_iter: 10000
  n_particles: 10
  nn_prior_std: 3.8e+00
  noise_std: 2.8e-03
  val_fraction: 1.0e-01
  weight_decay: 3.0e-07
  width: 64
metrics:
  test_nll: -2.2e+00
  test_rmse: 5.7e-02
