config:
  activation: elu
  bandwidth: 1.3e-03
  batch_size: 8
  coeff_cross_entropy: 1.4e-02
  coeff_entropy: 9.0e-03
  coeff_prior: 1.6e-01
  depth: 5
  early_stopping_metric: val_nll
  early_stopping_min_delta: 1.0e-04
  early_stopping_mode: min
  early_stopping_patience: 3000
  enable_early_stopping: true
  learning_rate: 7.0e-04
  likelihood_prior_mean: 4.9e-02
  likelihood_prior_std: 2.6e-03
  n_iter: 10000
  n_particles: 5
  nn_prior_std: 2.8e+00
  noise_std: 4.4e-04
  prior_noise_std: 5.6e-04
  ssge_bandwidth: 4.6e-01
  ssge_eta: 2.5e-02
  ssge_n_eigen: 16
  val_fraction: 1.0e-01
  weight_decay: 2.7e-08
  width: 64
metrics:
  checkpoint_dir_name: null
  config:
    activation: elu
    bandwidth: 1.3e-03
    batch_size: 8
    coeff_cross_entropy: 1.4e-02
    coeff_entropy: 9.0e-03
    coeff_prior: 1.6e-01
    depth: 5
    early_stopping_metric: val_nll
    early_stopping_min_delta: 1.0e-04
    early_stopping_mode: min
    early_stopping_patience: 3000
    enable_early_stopping: true
    learning_rate: 7.0e-04
    likelihood_prior_mean: 4.9e-02
    likelihood_prior_std: 2.6e-03
    n_iter: 10000
    n_particles: 5
    nn_prior_std: 2.8e+00
    noise_std: 4.4e-04
    prior_noise_std: 5.6e-04
    ssge_bandwidth: 4.6e-01
    ssge_eta: 2.5e-02
    ssge_n_eigen: 16
    val_fraction: 1.0e-01
    verbose: 0
    weight_decay: 2.7e-08
    width: 64
  date: 2025-09-18_11-07-39
  done: true
  experiment_tag: 1_activation=elu,bandwidth=0.0013,batch_size=8,coeff_cross_entropy=0.0136,coeff_entropy=0.0090,coeff_prior=0.1617,depth=5,learning_rate=0.0007,likelihood_prior_mean=0.0494,likelihood_prior_std=0.0026,n_particles=5,nn_prior_std=2.8472,noise_std=0.0004,prior_noise_std=0.0006,ssge_bandwidth=0.4556,ssge_eta=0.0249,ssge_n_eigen=16,weight_decay=0.0000,width=64
  hostname: Georgess-Mac-Studio.local
  iterations_since_restore: 52
  node_ip: 127.0.0.1
  pid: 63353
  test_nll: 1.3e+02
  test_rmse: 1.0e+00
  time_since_restore: 1.2e+02
  time_this_iter_s: 3.2e-03
  time_total_s: 1.2e+02
  timestamp: 1758186459
  training_iteration: 52
  trial_id: '94978_00001'
  val_nll: 1.2e+02
  val_rmse: 9.4e-01
