config:
  activation: elu
  bandwidth: 5.0e-02
  batch_size: 8
  depth: 2
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 3.0e-04
  likelihood_prior_mean: 2.1e-04
  likelihood_prior_std: 3.5e-02
  n_iter: 10000
  n_particles: 10
  nn_prior_std: 6.0e-01
  noise_std: 7.9e-03
  val_fraction: 1.0e-01
  weight_decay: 2.0e-07
  width: 64
metrics:
  test_nll: 4.9e-01
  test_rmse: 8.1e-01
