config:
  activation: elu
  bandwidth: 1.6e-02
  batch_size: 32
  coeff_cross_entropy: 6.2e-02
  coeff_entropy: 2.7e-03
  coeff_prior: 2.4e+00
  depth: 4
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 4.3e-03
  likelihood_prior_mean: 1.9e-04
  likelihood_prior_std: 2.2e-03
  n_iter: 10000
  n_particles: 15
  nn_prior_std: 8.6e-01
  noise_std: 7.9e-03
  prior_noise_std: 1.2e-05
  ssge_bandwidth: 1.5e+00
  ssge_eta: 9.3e-03
  ssge_n_eigen: 4
  val_fraction: 1.0e-01
  weight_decay: 4.9e-06
  width: 128
metrics:
  test_nll: -1.8e+00
  test_rmse: 1.0e-01
