config:
  activation: tanh
  bandwidth: 1.3e-02
  batch_size: 16
  depth: 4
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 1.6e-03
  likelihood_prior_mean: 4.6e-03
  likelihood_prior_std: 2.8e-02
  n_iter: 10000
  n_particles: 5
  nn_prior_std: 1.0e+00
  noise_std: 9.0e-02
  val_fraction: 1.0e-01
  weight_decay: 3.5e-08
  width: 128
metrics:
  test_nll: -1.5e+00
  test_rmse: 1.1e-01
