config:
  activation: elu
  bandwidth: 2.4e-03
  batch_size: 32
  coeff_cross_entropy: 4.2e-02
  coeff_entropy: 9.2e-02
  coeff_prior: 1.2e+00
  depth: 4
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 5.3e-03
  likelihood_prior_mean: 6.2e-03
  likelihood_prior_std: 5.5e-04
  n_iter: 10000
  n_particles: 10
  nn_prior_std: 5.5e-01
  noise_std: 1.6e-04
  prior_noise_std: 1.2e-04
  ssge_bandwidth: 1.3e-01
  ssge_eta: 3.6e-03
  ssge_n_eigen: 6
  val_fraction: 1.0e-01
  weight_decay: 2.1e-06
  width: 64
metrics:
  test_nll: 1.1e+02
  test_rmse: 5.2e-02
