config:
  activation: relu
  bandwidth: 1.1e-03
  batch_size: 32
  depth: 4
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 2.0e-04
  likelihood_prior_mean: 5.8e-03
  likelihood_prior_std: 2.2e-04
  n_iter: 10000
  nn_prior_std: 7.2e-01
  noise_std: 1.1e-02
  val_fraction: 1.0e-01
  weight_decay: 2.9e-07
  width: 64
metrics:
  test_nll: -1.3e+00
  test_rmse: 8.5e-02
