config:
  activation: relu
  bandwidth: 9.8e-03
  batch_size: 16
  depth: 2
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 4.8e-03
  likelihood_prior_mean: 1.2e-02
  likelihood_prior_std: 4.2e-04
  n_iter: 10000
  n_particles: 20
  nn_prior_std: 1.4e+00
  noise_std: 1.2e-02
  val_fraction: 1.0e-01
  weight_decay: 8.1e-07
  width: 128
metrics:
  test_nll: -1.3e+00
  test_rmse: 5.4e-02
