config:
  activation: elu
  bandwidth: 1.3e-03
  batch_size: 16
  depth: 4
  early_stopping_metric: val_nll
  early_stopping_min_delta: 0.0e+00
  early_stopping_mode: min
  early_stopping_patience: 1000
  enable_early_stopping: true
  learning_rate: 8.7e-03
  likelihood_prior_mean: 3.2e-04
  likelihood_prior_std: 4.0e-02
  n_iter: 10000
  n_particles: 50
  nn_prior_std: 6.9e-01
  noise_std: 2.8e-02
  val_fraction: 1.0e-01
  weight_decay: 5.9e-05
  width: 32
metrics:
  test_nll: -2.4e+00
  test_rmse: 5.6e-02
